#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-systemd
Version  : 235
Release  : 34
URL      : https://github.com/systemd/python-systemd/archive/v235/python-systemd-235.tar.gz
Source0  : https://github.com/systemd/python-systemd/archive/v235/python-systemd-235.tar.gz
Summary  : Systemd interfaces wrapper
Group    : Development/Tools
License  : LGPL-2.1
Requires: python-systemd-filemap = %{version}-%{release}
Requires: python-systemd-lib = %{version}-%{release}
Requires: python-systemd-license = %{version}-%{release}
Requires: python-systemd-python = %{version}-%{release}
Requires: python-systemd-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pkgconfig(libsystemd)
BuildRequires : pkgconfig(systemd)

%description
python-systemd
===============
Python module for native access to the systemd facilities. Functionality
is separated into a number of modules:
- `systemd.journal` supports sending of structured messages to the journal
and reading journal files,
- `systemd.daemon` wraps parts of `libsystemd` useful for writing daemons
and socket activation,
- `systemd.id128` provides functions for querying machine and boot identifiers
and a lists of message identifiers provided by systemd,
- `systemd.login` wraps parts of `libsystemd` used to query logged in users
and available seats and machines.

%package filemap
Summary: filemap components for the python-systemd package.
Group: Default

%description filemap
filemap components for the python-systemd package.


%package lib
Summary: lib components for the python-systemd package.
Group: Libraries
Requires: python-systemd-license = %{version}-%{release}
Requires: python-systemd-filemap = %{version}-%{release}

%description lib
lib components for the python-systemd package.


%package license
Summary: license components for the python-systemd package.
Group: Default

%description license
license components for the python-systemd package.


%package python
Summary: python components for the python-systemd package.
Group: Default
Requires: python-systemd-python3 = %{version}-%{release}

%description python
python components for the python-systemd package.


%package python3
Summary: python3 components for the python-systemd package.
Group: Default
Requires: python-systemd-filemap = %{version}-%{release}
Requires: python3-core
Provides: pypi(python_systemd)

%description python3
python3 components for the python-systemd package.


%prep
%setup -q -n python-systemd-235
cd %{_builddir}/python-systemd-235
pushd ..
cp -a python-systemd-235 buildavx2
cp -a python-systemd-235 buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1672198113
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx"
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/python-systemd
cp %{_builddir}/python-systemd-%{version}/LICENSE.txt %{buildroot}/usr/share/package-licenses/python-systemd/01a6b4bf79aca9b556822601186afab86e8c4fbf
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files filemap
%defattr(-,root,root,-)
/usr/share/clear/filemap/filemap-python-systemd

%files lib
%defattr(-,root,root,-)
/usr/share/clear/optimized-elf/other*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/python-systemd/01a6b4bf79aca9b556822601186afab86e8c4fbf

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
